name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    name: Deploying everything to staging cluster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > /home/runner/ssh.key
          chmod 600 /home/runner/ssh.key
          ls -l /home/runner/ssh.key

          mkdir -p /home/runner/.ssh
          ssh-keyscan -H 13.50.245.231 >> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/.ssh

          ssh -o StrictHostKeyChecking=no -i /home/runner/ssh.key ubuntu@13.50.245.231 << 'EOF'
         

          cd ~/recruitmentapp
          git fetch origin main
          git reset --hard origin/main

          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart ws-server
          pm2 restart web-server
          EOF


