name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    name: Deploying everything to staging cluster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" &> ~/ssh.key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/.ssh
          ssh -i ssh.key ubuntu@13.50.245.231 

          cd recruitmentapp
          git fetch origin main
          git reset --hard origin/main

          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart ws-server
          pm2 restart web-server


