name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    name: Deploying everything to staging cluster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ssh.key
          chmod 600 ssh.key

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh.key ubuntu@13.50.245.231 << 'EOF'
          export PATH=$PATH:/usr/local/bin
          cd recruitmentapp
          git fetch origin
          git checkout main
          git reset --hard origin/main
          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart ws-server
          pm2 restart web-server
          EOF

